version: '2.1'

services:
    server:
        build:
            context: docker
            dockerfile: dockerfile 
        privileged: true
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
        command: bash -c "ping -c 1 $$(ip route show default | awk '/default/ {print $$3}') && ip -s -s neigh flush all && python /elocal/src/tcp_server.py & bash"
    middle:
        build:
            context: docker
            dockerfile: dockerfile
        privileged: true
        depends_on:
            - "server"
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
        command: bash -c "tcpdump -SnntXX tcp && timeout 10 python3 /elocal/src/arp_poison.py & bash"
    client:
        build:
            context: docker
            dockerfile: dockerfile
        privileged: true
        depends_on:
            - "server"
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
        command: bash -c "sleep 4 && python /elocal/src/tcp_client.py -s tema3_server_1 & bash"


networks:
    dmz: {}
