version: '2.1'

services:
    router:
        build:
            context: docker
            dockerfile: dockerfile 
        privileged: true
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
        command: bash -c "ping -c 1 tema3_server_1 && sleep 1 && ip -s -s neigh flush all && sleep 2 && arp -a & bash"
    server:
        build:
            context: docker
            dockerfile: dockerfile 
        privileged: true
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
        command: bash -c "ping -c 1 tema3_router_1 && sleep 1 && ip -s -s neigh flush all && sleep 2 && arp -a & bash"
    middle:
        build:
            context: docker
            dockerfile: dockerfile
        privileged: true
        depends_on:
            - "server"
            - "router"
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
        command: bash -c "tcpdump -SnntXX tcp & timeout 10 python3 /elocal/src/arp_poison.py -g tema3_router_1 -t tema3_server_1 & bash"
    client:
        build:
            context: docker
            dockerfile: dockerfile
        privileged: true
        depends_on:
            - "server"
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
        command: bash


networks:
    dmz: {}
